In [ ]:
import numpy as np
square = []
room = []
price = []
homeList = []
for x in range(1,11,1):
    square.append(x*30)
    room.append(x)
    price.append(x*70000)
homeList.append(square)
homeList.append(room)
homeList.append(price)
print(homeList)
homeArray = np.array(homeList)
print(homeArray)
homeArray = homeArray.T
print(homeArray)
print(homeArray.shape)
#when we run the code, it displays (10,3). It means that we have an array with 10 elements and each one of these elements also
#has three elements. This array has two dimension that created by 10 rows and 3 coloumns.


In [7]:
import numpy as np

def oneToZero (originArray):
    for x in range(0, originArray.shape[0]):
        for y in range(0, originArray.shape[1]):
            if(x%2 == 0) & (y%2 == 0):
                originArray[x,y] = 0
    return originArray

row = int(input("Please enter row number: "))
coloumn = int(input("Please enter coloumn number: "))
arrayOrigin = np.empty((coloumn,row))
for x in range(coloumn):
    for y in range(row):
        arrayOrigin[x][y] = 1
print(arrayOrigin)
print(oneToZero(arrayOrigin))

Please enter row number: 5
Please enter coloumn number: 5
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0.]]
